namespace SmartHttpClient.Models;

// ----------------------------------------------------------------------------------------

class Problem
{
    /// <summary>
    /// A URI reference that identifies the problem type.
    /// </summary>
    public string? Type { get; init; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string? Title { get; init; }

    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    public int? StatusCode { get; init; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; init; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string? Instance { get; init; }

    /// <summary>
    /// A collection of additional key-value pairs with custom information about the problem.
    /// </summary>
    public IDictionary<string, object>? Extensions { get; set; }
}
